### ISSUE TITLE
Newer version

### ISSUE THREAD

**Issue by daybugging** [helhum/typo3-secure-web#10]
Hey there,
I guess it's not a problem to require typo3-core 8.7.13 manually besides typo3-secure-web? Otherwise an update to the latest v8 version would be welcome!

Thanks!

**Comment by helhum** [comment]
Hey @daybugging. Thanks for your report.
Unfortunately I'm not sure what you are asking for or which issue you face.
Can you elaborate?

**Comment by S1SYPHOS** [comment]
I guess she wants to use `typo3-secure-web`, but require a higher `typo3/cms-core` version (eg `8.7.13`).

**Comment by daybugging** [comment]
I tested it successfully, thanks again for coming back at me!
