### ISSUE TITLE
Missing symlink for typo3/sysext/core/Configuration/DefaultConfiguration.php ???

### ISSUE THREAD

**Issue by DavidBruchmann** [helhum/typo3-secure-web#13]
The error occurred after installation, currently it can't be reproduced.

**Describe the bug**
With installation by composer in the site-tree error-messages are shown that `private/typo3/sysext/core/Configuration/DefaultConfiguration.php` is missing. Creating a symlink for it in the public folder solves the issue.

**To Reproduce**
1. Install a current version of TYPO3 with composer.
2. Open the backend and look at the area for the page-tree.
3. If required create a sample page, I remarked it with existing database and pagetree.
4. See if the error error between icons above pagetree and pagetree itself orrurs.

**Expected behavior**
Display without errors.

**Desktop (please complete the following information):**
 - OS: Win 10 (with working auto-created junctions)
 - Browser chrome, current Version 71.0.3578.98 (Official Build) (64-bit)
 - Version 0.2.7)

**Additional context**
After creating a symlink in the folder `puiblic/typo3/sysext/core/Configuration/DefaultConfiguration.php` the error disappeared.
For a screenshot I disabled the symlink but can't reproduce the error anymore.

Checking all modules in BE I never remarked any other faults.

**Comment by helhum** [comment]
There isn't a missing link. This directory must not exist in public path.
The reason for that is legacy code on TYPO3 side and a way to deal with that, which I just added.

So this should be fixed now

**Comment by DavidBruchmann** [comment]
Great that you could use my report despite I couldn't reproduce it.
