### ISSUE TITLE
Wrong autoload Path

### ISSUE THREAD

**Issue by scriptserv** [helhum/typo3-secure-web#14]
If i install your extension with composer i get the following error, because TYPO3 can`t find its autoload file:

Warning: require(C:\xampp\htdocs\PROJECT_NAME\web/../../../../../../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\PROJECT_NAME\web\index.php on line 22

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\PROJECT_NAME\web/../../../../../../vendor/autoload.php' (include_path='.;c:\php\includes') in C:\xampp\htdocs\PROJECT_NAME\web\index.php on line 22

System:
Win10 - newest updates
Composer 1.8.0
TYPO3 9.5.3

My Composer.json looks like this:

```json
{
  "name": "xxx/xxxxxx",
  "type": "metapackage",
  "description": "TYPO3 Composer installation",
  "authors": [
    {
      "name": "Dennis",
      "role": "Developer"
    }
  ],
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": {
    "typo3composer": {
      "type": "composer",
      "url": "https://composer.typo3.org/"
    },
    "local": {
      "type": "path",
      "url": "local/*"
    }
  },
  "require": {
   "typo3/minimal": "9.5.*",

    "typo3/cms-adminpanel": "9.5.*",
    "typo3/cms-belog": "9.5.*",
    "typo3/cms-beuser": "9.5.*",
    "typo3/cms-fluid-styled-content": "9.5.*",
    "typo3/cms-impexp": "9.5.*",
    "typo3/cms-indexed-search": "9.5.*",
    "typo3/cms-info": "9.5.*",
    "typo3/cms-lowlevel": "9.5.*",
    "typo3/cms-recycler": "9.5.*",
    "typo3/cms-redirects": "9.5.*",
    "typo3/cms-reports": "9.5.*",
    "typo3/cms-rte-ckeditor": "9.5.*",
    "typo3/cms-scheduler": "9.5.*",
    "typo3/cms-seo": "9.5.*",
    "typo3/cms-setup": "9.5.*",
    "typo3/cms-tstemplate": "9.5.*",
    "typo3/cms-viewpage": "9.5.*",

    "typo3-ter/cookie-hint": "2.0.*",
    "in2code/powermail": "^7.0",
    "georgringer/news": "^7.0",
    "friendsoftypo3/frontend-editing": "^1.4",
    "helhum/typo3-console": "^5.5",
    "helhum/typo3-secure-web": "^0.2",
    "undefined/translate-locallang": "^2.3",

    "xxx/localExtension1": "*",
    "xxx/localExtension2": "^0.7",
    "xxx/localExtension3": "^1.0"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "web",
      "root-dir": "private"
    }
  }
}
```

**Comment by helhum** [comment]
Can you give me a directory listing of `C:\xampp\htdocs\PROJECT_NAME\web\` and the file contents of `C:\xampp\htdocs\PROJECT_NAME\web\index.php`? Thanks.

It works flawlessly for me with the composer.json you posted (with the private extensions removed)

**Comment by scriptserv** [comment]
The listing of "C:\xampp\htdocs\PROJECT_NAME\web\":
`08.01.2019  08:59            13.768 .htaccess
18.12.2018  16:52    <JUNCTION>     fileadmin [C:\xampp\htdocs\PROJECT_NAME\private\fileadmin]
08.01.2019  09:28               980 index.php
08.01.2019  07:36    <DIR>          typo3
08.01.2019  08:41    <DIR>          typo3conf
18.12.2018  16:52    <DIR>          typo3temp`

And "C:\xampp\htdocs\PROJECT_NAME\web\index.php":
`<?php
/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

// Exit early if php requirement is not satisfied.
if (PHP_VERSION_ID < 70200) {
    die('This version of TYPO3 CMS requires PHP 7.2 or above');
}

// Set up the application for the frontend
call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(0, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_FE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Frontend\Http\Application::class)->run();
});`

It works for me on my macbook without any problems too, it just seems to appear on my windows pc

**Comment by helhum** [comment]
The error message you posted above, does not match the code you posted from the index.php

Are you sure your web server is executing the correct file?

**Comment by scriptserv** [comment]
Sorry for the late answer.

The correct Code from index.php was:

// Set up the application for the frontend
```
call_user_func(function () {
    $classLoader = require __DIR__ . '/../../../../../../vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(0, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_FE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Frontend\Http\Application::class)->run();
});
```
DocumentRoot "C:/xampp/htdocs/PORJECT_NAME/web"

**Comment by helhum** [comment]
@scriptserv The thing is, the new code you posted is wrong, the old code you posted was correct. My question now is: Where did you get the content of the correct code (because this is the correctly generated one), when you are saying the code you see looks like you posted today :)

**Comment by scriptserv** [comment]
Hi Helmut, 
sorry for the confusion...

```
The error was in my composer.json the following line:
"extra": {
    "typo3/cms": {
      **"cms-package-dir": "{$vendor-dir}/typo3/cms",**
      "web-dir": "web",
      "root-dir": "private"
    }
  }
```

As soon as i removed this line, deleted everything (except the local folder) and installed everything again with composer now everything works...
I'm really sorry for the inconveniences... Great work by the way! :)

My index.php now looks like this:

```
// Set up the application for the frontend
call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    chdir(getenv('TYPO3_PATH_ROOT'));
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(0, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_FE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Frontend\Http\Application::class)->run();
});
```
