### ISSUE TITLE
Should I commit public/.htaccess to git?

### ISSUE THREAD

**Issue by josefglatz** [helhum/typo3-secure-web#17]
Is this intended when I use this composer package?

**Comment by helhum** [comment]
It depends on your project structure and workflows.
If you use Apache webserver and allow `.htaccess` overrides in its configuration and have a workflow that must allow developers with access to the project repository to modify webserver configuration with an `.htaccess` file, it is legitimate to commit this file to your repository.

Security (and performance) wise it would be better to disable `.htaccess` parsing completely in Apache webserver and add the required rules directly to the vHost configuration.
This of course does not work for hosting environments where you don't have direct access to such vHost configuration. In such case I'd commit the .htaccess to version control, but make sure it is not writable by the webserver/ PHP process during deployment for additional security.

HTH
