### ISSUE TITLE
Question: Root-dir naming?

### ISSUE THREAD

**Issue by ursbraem** [helhum/typo3-secure-web#18]
Just wondering: the docs state to specify 

`   "root-dir": "private",`

Until now, I've always done it like this. But could I also name the root-dir freely?

`   "root-dir": "whatever",` ?

Or even

`   "root-dir": "",` ?

**Comment by helhum** [comment]
private is default, but naming is totally up to you. I wouldn’t recommend leaving it empty (which would mean composer root) though.

**Comment by ursbraem** [comment]
Nice! Because I have already a directory named private, so I'd rather go for something more specific. I think `typo3-secure-web` might fit.

Thanks!
