### ISSUE TITLE
v3 breaks entry script detection?

### ISSUE THREAD

**Issue by infabo** [helhum/typo3-secure-web#22]
As a simple update of just this package, breaks install:generatepackagestates

![image](https://user-images.githubusercontent.com/3999104/104051137-eff46a80-51e7-11eb-8914-989f48aae99a.png)

Looks fine according to the commit that states, the dependency to this helum composer-setup package is obsolete now in 9.5.20+.

But this simple and fine change has the true power to break my deployment right hard:

![image](https://user-images.githubusercontent.com/3999104/104051026-c3d8e980-51e7-11eb-9c37-1b1934cbf385.png)

I don't know how to get more verbose output than "-1" of this autocommand triggered "install:generatepackagestates" as I am using typo3-console/composer-auto-commands.

But I modified my project composer.json and removed typo3-console/composer-auto-commands for testing and called install:generatepackagestates explictly.

Now I got:

![image](https://user-images.githubusercontent.com/3999104/104051996-52019f80-51e9-11eb-83d5-48759ddf86ff.png)

`Unable to determine path to entry script.`

Seems like the "merge" of the code from `helhum/typo3-composer-setup` has some open issues.

PS:
TYPO3 9.5.24

**Comment by helhum** [comment]
Thanks for the report. A fixed version is released.

> As a simple update of just this package, breaks install:generatepackagestates
> But this simple and fine change has the true power to break my deployment right hard:

Side note: Upgrading from 0.2.x to 0.3.0 may include breaking changes according to [semantic versioning](https://semver.org/#spec-item-4). You may want to change your version constraint accordingly for your production systems.

In this case though, this breakage was unintentional and "just" a bug.
So thanks for discovering and reporting it!

**Comment by infabo** [comment]
Thanks @helhum.

Forgot to mention that local on DDEV all was working well. install:generatepackagestates ran successfully as well.

The issue first appeared afterwards in the gitlab CI/CD.

Ad semver: EVERY 0.x.y release can include breaking changes. So even 0.2.8 to 0.2.9.

**Comment by helhum** [comment]
> Forgot to mention that local on DDEV all was working well. install:generatepackagestates ran successfully as well.
> 
> The issue first appeared afterwards in the gitlab CI/CD.

Yeah. It required two composer dumpautoload runs to create all entry scripts. 

> Ad semver: EVERY 0.x.y release can include breaking changes. So even 0.2.8 to 0.2.9.

yeah, true. I remembered differently and do it differently in practice though.
