### ISSUE TITLE
Question: Empty root-dir possible?

### ISSUE THREAD

**Issue by syssi** [helhum/typo3-secure-web#23]
The folder name "private" is a bit misleading because the composer root contains private files too. I would like to use the composer root as `root-dir`. I've seen your feedback here:

https://github.com/helhum/typo3-secure-web/issues/18

Could you explain your recommendation? Thanks in advance!

**Comment by helhum** [comment]
For now TYPO3 needs a dedicated directory to live in (where folders like typo3 and typo3conf reside). I can not recommend to to mix this special folder with the root of your composer project and have no clue what other side effects this would have other than polluting the project root folder with TYPO3 stuff. 

My goal would be to keep a dedicated folder for that until typo3 can work with extensions installed in the regular vendor folder, the this dedicated folder goes away naturally.
