### ISSUE TITLE
TypeError Problem with v0.3.0+

### ISSUE THREAD

**Issue by tomasnorre** [helhum/typo3-secure-web#24]
Hi, 

When using the `helhum/typo3-secure-web` with the `v0.3.0+` versions I get following error. When running `composer du` or the `composer install` which executes the `composer du`.

```shell 
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Composer\Installer\InstallationManager::getInstallPath() must implement interface Composer\Package\PackageInterface, null given, called in /composer-2.1-secure-web-test/vendor/helhum/typo3-secure-web/src/Composer/Typo3EntryPointFinder.php on line 44 and defined in phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:570
Stack trace:
#0 /composer-2.1-secure-web-test/vendor/helhum/typo3-secure-web/src/Composer/Typo3EntryPointFinder.php(44): Composer\Installer\InstallationManager->getInstallPath()
#1 /composer-2.1-secure-web-test/vendor/helhum/typo3-secure-web/src/Composer/InstallerScripts.php(36): Helhum\Typo3SecureWeb\Composer\Typo3EntryPointFinder->find()
#2 /composer-2.1-secure-web-test/vendor/typo3/cms-composer-installers/src/Plugin/Core/ScriptDispatcher.php(108): Helhum\Typo3SecureWeb\Composer\InstallerScripts::register()
#3 /composer-2.1-secure-web-test/vendor/typo3/ in phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php on line 570
```

## How to reproduce this? 

PHP 7.2 or 7.4
Composer 1.10.22 or 2.x.y (have tested with 2.0.14 and 2.1.3)

my composer.json
```json
{
    "require": {
        "helhum/typo3-secure-web": "0.3.0",
        "typo3/cms-core": "^10.4"
    },
    "extra": {
        "typo3/cms": {
            "root-dir": "private",
            "web-dir": "public"
        }
    }
}
```

If I switch back to version 0.2.11 the problem isn't there, so it's introduced after that. 

Please let me know if I can help in any way, either with fixing or providing more information.

**Comment by tomasnorre** [comment]
I have found the problem. 

If I require following as well, it doesn't break. 

```shell
        "typo3/cms-frontend": "^10.4",
        "typo3/cms-backend": "*",
        "typo3/cms-install": "*"
```

As the `helhum/typo3-secure-web` requires these 3 packages, I would suggest adding them to the composer.json for the `helhum/typo3-secure-web`, unless I'm missing some logic reason for not doing so. 

I know the packages are installed in 99% of the time, but in our case it wasn't. 

I will make a PR with this, to make it a little faster to have it fixed, If you don't agree, I would be happy to know why :) 

Thanks.

**Comment by helhum** [comment]
Technically you are correct. On the other hand, TYPO3 does not really work if any of these extensions are missing. The only thing is, that this fact isn't properly reflected in TYPO3's packages and documentation.

If you want to install TYPO3 with Composer you **MUST** require `typo3/minimal`, or all extensions that are required in this meta package.

So the best fix would be figuring out how to communicate and implement this fact for TYPO3, otherwise other areas may break for people not requiring these extensions.


That said, I still find it useful to handle the case here, when any of these packages isn't installed, for when TYPO3 itself lifts such requirements and will work e.g. without frontend.

**Comment by tomasnorre** [comment]
Thanks for your update. 

I just checked our project again, and we had them installed too, so perhaps we were seeing another problem that I didn't pay correct attention too. 

We experienced it after updating to composer 2.1 from 2.0.13, so I might mix up 2 things atm. (sorry for that)

**Comment by helhum** [comment]
> so perhaps we were seeing another problem that I didn't pay correct attention too.

So the error message you were seeing was different from the one you posted here?

**Comment by tomasnorre** [comment]
I believe so, after see what the "problem" was here. Unfortunately, I don't have the build log from back then. So will have to switch my composer version in my build setup to reproduce.

But I'm pretty certain that it's to different issues.
