### ISSUE TITLE
Public files are copied instead of symlinked

### ISSUE THREAD

**Issue by hirnschmalz** [helhum/typo3-secure-web#28]
I'm running my TYPO3 instance in an Alpine Docker container. For some strange reason the public files are copied from the `private` to the `public` folder. Since this is obviously done only once a lot of files are missing (e.g. inside `public/typo3temp/assets`).

Does anyone have any hints for me?

**Comment by helhum** [comment]
There is no code in this package that copies folders.
Besides that, it is hard to say anything without having any information about your setup (Except "Alpine Docker").

> Does anyone have any hints for me?

Maybe try in TYPO3 Slack to get direct help or support with faster round trip times?

**Comment by Kayu84** [comment]
@hirnschmalz : maybe, you use an installation on a system (docker instance) that doesn't support symlinks?!
I'm not sure if it could be a weird reason that then tries to copy the source instead.... but I know in some situations when trying to backup folders (symlinks included)... e.g.: mac -> external windows formatted disk, the symlinks are copied as "resource" copies.

**Comment by hirnschmalz** [comment]
I wasn't able to reproduce this in other installations. So I guess something weird happened in this special case.
