### ISSUE TITLE
no symlink created (fileadmin) but a folder - Assumption: DDEV mutagen

### ISSUE THREAD

**Issue by Kayu84** [helhum/typo3-secure-web#29]
I am not sure what is happening here....
  in my first situation I have a system where the folder "private/fileadmin" exists, after the installation (composer) there is a "public/fileadmin" **folder**.
In a second attempt I removed "private/fileadmin", after installation the private folder was created again, but I got the following error:

  `Failed to create "symbolic" link from "../private/fileadmin" to "/var/www/html/public/fileadmin": symlink(): File exists`

  As a brainstorm, I was wondering about file exists without any hint from `ls`....
  
  After disabling mutagen and a ddev restart I was able to remove the old folders, install from the new ones (composer) and voila, the symlink exists.

But the question remains: Why is a folder created instead?

**Comment by Kayu84** [comment]
Problem solved: https://github.com/drud/ddev/pull/4061#issuecomment-1201760762

**Comment by helhum** [comment]
Thanks @Kayu84 !

**Comment by benjamingries** [comment]
Hi @Kayu84,

Could you specify which path to put in the upload_dir option? 

We have a setup with a web/private and a web/public directory. The docroot in DDEV is web/public.

Many thanks and best regards
Benjamin

**Comment by Kayu84** [comment]
Hi @benjamingries ,

This is what i'm using in the config.yaml
`upload_dir: ../private/fileadmin`

Should work for your setup too.
