### ISSUE TITLE
[solved] How I can use cli_dispatch.phpsh? 

### ISSUE THREAD

**Issue by ohartwig** [helhum/typo3-secure-web#4]
In some Extension (e.g. ) the deprecated entry point cli_dispatch.phpsh is still in use, how I can use them with typo3-secure-web?

**Comment by ohartwig** [comment]
Thanks to @helhumfor his solution of the problem.

- Add a new File to `/private/typo3/cli_dispatch.phpsh`
- Add this PHP-Skript in to this File https://gist.github.com/ohartwig/8aaedbeb4bfaf301b5fc97a0e47d70e2
- Make cli_dispatch.phpsh executable `chmod +x private/typo3/cli_dispatch.phpsh`

For some Skripts you have to add a symlink from your public directory to your private directory.

private `private` is my private-directory!

**Comment by DanielSiepmann** [comment]
We switched to `vendor/bin/typo3cms scheduler:run` which works out of the box.

**Comment by helhum** [comment]
> For some scripts you have to add a symlink from your public directory to your private directory.

@ohartwig can you elaborate on that? I don't understand it and would like to be sure you don't expose sth to a public directory if that is not required

**Comment by helhum** [comment]
Can now conveniently solved with https://github.com/pagemachine/typo3-composer-legacy-cli
