### ISSUE TITLE
It should be allowed for fileadmin to link to a nonexisting target

### ISSUE THREAD

**Issue by ervaude** [helhum/typo3-secure-web#9]
https://github.com/helhum/typo3-secure-web/blob/0f29709bf56ea5ff5db37cfcfb649cae31a4703d/src/Composer/InstallerScript/WebDirectory.php#L114-L122

The `ensureDirectoryExists()` call for fileadmin throws an exception if private/fileadmin is a symlink to a nonexisting folder. This is not a rare case since fileadmin is often linked to a folder outside the git root of a project and deployed as such. During the deployment process where the project is build on a dedicated deployment server it is possible that the target of the symlink does not exist.

To reproduce just create private/fileadmin as a symlink to a nonexisting folder and `composer install`.

A quick workaround:
```
try {
  $this->filesystem->ensureDirectoryExists($source);
} catch (\RuntimeException $e) {
  if (!is_link($source)) {
    throw $e;
  }
}
```
There may be a better solution ;)

**Comment by helhum** [comment]
How about skipping symlink creation if target is already a link?
Then you could add public/fileadmin as link as well.

**Comment by ervaude** [comment]
Sure, that should work just fine.

But maybe still rather catch the Exception and proceed with a warning than exit with an error.

**Comment by helhum** [comment]
Finally fixed. Sorry that this took so long.
